/*******************************************************************************
* This file was generated by UI Builder.
* User should hand edit this file.
********************************************************************************/

#include "app_main.h"
#include "view_data.h"
#include "uib_app_manager.h"
#include "uib_views.h"
#include "uib_views_inc.h"

typedef struct _uib_view3_control_context {
	/* add your variables here */

} uib_view3_control_context;

/**
 * @brief the user clicked the button (press/release).
 *
 * @param vc It is context of the view that this event occurred on. It has all of UI components that this view consist of.
 * @param obj It is UI component itself that emits the event signal.
 * @param event_info
 * 		event_info is NULL
 *
 */

void view3_button1_onclicked(uib_view3_view_context *vc, Evas_Object *obj, void *event_info) {
	//Invoked at the start of wrapper function view3_connection_view3_button1_onclicked

}

void view3_button1_onclicked_post(void* param, uib_view3_view_context *vc, Evas_Object *obj, void *event_info) {
	//Invoked post wrapper function view3_connection_view3_button1_onclicked

}
